clientcontroller/babylon.go, go.mod, go.sum, itest/babylon_node_handler.go, itest/e2e_test.go, itest/test_manager.go, tools/go.mod, tools/go.sum, types/stakingparams.go
This PR fixed #206. The approach is inspired by [btc-staker](https://github.com/babylonchain/btc-staker) which constructs covenant sigs internally in e2e tests instead of using a covenant-emulator instance.
=> chore: Remove dependency on covenant-emulator

docs/eots.md, docs/finality-provider.md
As we have keyring backend of `test` as the default value. This should be consistent with the docs. Also, due to issue #145, `file` keyring backend is not well supported (user needs to type the passphrase prompted from the eotsd's terminal).
=> fix(doc): Inconsistency of keyringbackend in doc

finality-provider/service/chain_poller.go
In the following scenario:
1. Fast sync starts
2. A new block is retrieved by the poller
3. Fast sync ends
Step 2, adds the new block to the poller blocks channel (which is not known to the fast sync process). However, at step 3, the fast sync process cleans up the block cache, leading to the new block getting lost.
=> fix: Only clean up blocks buffer up to the fast-synced height

clientcontroller/babylon.go
This PR fixed #223. This bug also affects fast-sync in the sense that it polls the best Comet block as the target block to catch up. Due to the laziness of CometBFT, by the time of polling, the voting power table might not be updated. Therefore, the voting power could be zero and the finality provider might set this block height as `LastProcessHeight` and will never vote for this block.
This PR changed the `QueryBestBlock` by first using the query from the finality module. If there's no indexed block in the finality module, it will fallback to using the query from the CometBFT
=> fix: Query best block causing flaky voting power result

clientcontroller/babylon.go, clientcontroller/retry_utils.go, clientcontroller/retry_utils_test.go, finality-provider/service/fp_instance.go, itest/e2e_test.go
This PR fixed #220. The bug is due to `nil` response will be returned if the error during retrying is expected.
=> chore: Fix panicking upon expected error during retrying

finality-provider/service/chain_poller.go, finality-provider/service/chain_poller_test.go, finality-provider/service/fp_instance.go
This PR potentially fixed #234. We need to ensure that after fast sync, the poller is still up-to-date. This PR ensures that the next height of the poller should not be set with a lower value.
=> fix(poller): Next height should not be set with a lower value

eotsmanager/cmd/eotsd/init.go
Fixes - https://github.com/babylonchain/finality-provider/issues/266
On building binary from latest commit on dev and `eotsd init`, I am getting this panic 
```
panic: provided data is not a pointer to struct
goroutine 1 [running]:
github.com/jessevdk/go-flags.(*Group).scanType(0x14000134aa0, 0x140005d7520)
/Users/gusin/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/group.go:403 +0x1cc
github.com/jessevdk/go-flags.(*Command).AddGroup(0x140004a1680, {0x10351109f, 0x13}, {0x0, 0x0}, {0x10381ab20, 0x140001fe978})
/Users/gusin/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/command.go:89 +0xe4
github.com/jessevdk/go-flags.NewParser({0x10381ab20, 0x140001fe978}, 0x16)
/Users/gusin/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:160 +0x184
main.initHome(0x140004b0dc0) …
```
=> fix: Fixes panic in eotsd init

docs/eots.md, eotsmanager/cmd/eotsd/daemon/flags.go, eotsmanager/cmd/eotsd/daemon/init.go, eotsmanager/cmd/eotsd/daemon/keys.go, eotsmanager/cmd/eotsd/daemon/start.go, eotsmanager/cmd/eotsd/main.go, eotsmanager/localmanager.go, eotsmanager/localmanager_test.go, finality-provider/service/app_test.go, finality-provider/service/fp_instance_test.go, finality-provider/service/fp_manager_test.go, itest/eotsmanager_handler.go, keyring/keyringcontroller_test.go
- Moved files to new package `daemon` to avoid having more than one file in `main` package
- Add new command `eotsd keys add` with the option to `--recover` from mnemonic  
- Set data dir on config to created data dir in `eotsd init` instead of the default
closes: #306
=> feat: eotsd keys add

clientcontroller/babylon.go, clientcontroller/babylon_consumer.go, clientcontroller/interface.go, finality-provider/service/app.go, finality-provider/service/app_test.go, finality-provider/service/chain_poller.go, finality-provider/service/chain_poller_test.go, finality-provider/service/fastsync.go, finality-provider/service/fastsync_test.go, finality-provider/service/fp_instance.go, finality-provider/service/fp_instance_test.go, finality-provider/service/fp_manager.go, finality-provider/service/fp_manager_test.go, itest/e2e_test.go, itest/test_manager.go
To support the EVM chain and keep Babylon as the staking hub, we need to split `ClientController` into two parts.
* `ClientController` includes the functions for the Babylon hub:
* `RegisterFinalityProvider`
* `QueryFinalityProviderVotingPower`
* `QueryLastFinalizedEpoch`
* ...
* `ConsumerController` includes the functions for the Consumer chain:
*  `SubmitFinalitySig`
* `QueryFinalityProviderVotingPower`
* `QueryBlock`
* ...
`make test `
```bash                                          
go test ./...
ok      github.com/babylonchain/finality-provider/clientcontroller      2.022s
ok      github.com/babylonchain/finality-provider/eotsmanager   7.521s
ok      github.com/babylonchain/finality-provider/eotsmanager/cmd/eotsd/daemon  6.552s
ok …
```
=> feat: Split into ClientController and ConsumerController

docs/eots.md
This commit updates the eots.md documentation to include the --keyring-backend file option in the eotsd sign-schnorr command example. This addition ensures that the command specifies the use of the file-based keyring backend for managing keys.
Changes:
- Added --keyring-backend file option to the eotsd sign-schnorr command example.
This enhancement improves clarity and accuracy in the documentation, ensuring users are aware of the necessary flag to specify the keyring backend.
=> Add keyring-backend option to sign-schnorr command in eots.md

eotsmanager/client/rpcclient.go, finality-provider/service/client/rpcclient.go, itest/e2e_test.go
Grpc/Protobuf dependencies were bumped in this commit
https://github.com/babylonchain/finality-provider/commit/b79ac3101a2ef8205b97a7d1a8a061fff792d03f#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R34-R35
due to which grps.Dial has become deprecated and causes lint failure. This pr replaces deprecated with grpc.NewClient
```
// Dial calls DialContext(context.Background(), target, opts...).
//
// Deprecated: use NewClient instead.  Will be supported throughout 1.x.
func Dial(target string, opts ...DialOption) (*ClientConn, error) {
return DialContext(context.Background(), target, opts...)
}
```
Lint doesn't fail in dev branch as it still uses old version of grpc
=> fix: fix lint/e2e error

finality-provider/service/errors.go, finality-provider/service/fp_instance.go, log/log.go
This PR fixed two issues #371 and #372  related to the retry loops:
* `retryCheckRandomnessUntilBlockFinalized ` can be returned if the block is finalized but the randomness does not exist. In this case, we should skip this block for submitting a finality vote. Otherwise, the submission will fail with `ErrPubRandNotExist`. The PR fixed this issue by introducing a `bool` indicating whether the target block is finalized or not.
* within the `retryCheckRandomnessUntilBlockFinalized` loop, if the randomness is never submitted, the loop will stall because the maximum retry time is only applied in errors. This PR addressed this by also limiting the time of retries if the randomness does not exist.
This PR also added an error type `ErrFinalityProviderShutDown` to close the retry loops gracefully …
=> chore: Fix issues in retry loops

cosmwasmclient/query/client.go
the code here adds `x-cosmos-block-height` metadata which is used to query historical data ([reference](https://docs.cosmos.network/main/user/run-node/interact-node#query-for-historical-state-using-grpcurl))
this is unnecessary and never used b/c it always passes 0 height
also `DefaultQueryOptions()` and `QueryOptions` are never used elsewhere (seems they are just dead code copied from [here](https://github.com/strangelove-ventures/lens/blob/v0.5.4/client/query/query_options.go))
```
make test
make test-e2e
```
=> refactor: remove unused config in wasmd client

clientcontroller/opstackl2/consumer.go
Implemented:
```Go
// QueryBlock queries the block at the given height
QueryBlock(height uint64) (*types.BlockInfo, error)
// QueryBlocks returns a list of blocks from startHeight to endHeight
QueryBlocks(startHeight, endHeight, limit uint64) ([]*types.BlockInfo, error)
// QueryLatestBlockHeight queries the tip block height of the consumer chain
QueryLatestBlockHeight() (uint64, error)
// QueryLatestFinalizedBlock returns the finalized L2 block from a RPC call
// TODO: return the BTC finalized L2 block, it is tricky
QueryLatestFinalizedBlock() (*types.BlockInfo, error)
```
TODO:
The `op-finality-gadget` contract needs support for the following queries.
```Go
// QueryActivatedHeight returns the activated height of the consumer chain
// error will be returned if the consumer chain has not …
```
=> feat: the queries for OPStack L2 consumer

clientcontroller/opstackl2/consumer.go, clientcontroller/opstackl2/msg.go
This PR implements these consumer queries of OPStack L2:
* QueryIsBlockFinalized
* QueryLastCommittedPublicRand
* QueryFinalityProviderVotingPower
=> feat: queries for OPStack L2

clientcontroller/babylon.go, clientcontroller/interface.go, finality-provider/service/app.go, finality-provider/service/app_test.go, finality-provider/service/types.go, testutil/mocks/babylon.go
This PR fixes the bug in rc where the consumer ID is not passed to the finality provider registration request.
PoC: I registered a consumer FP using this version successfully.
```
➜  finality-provider git:(release-euphrates-0.2.0-rc.1) ✗ babylond query btcstaking finality-provider ae19288a43b107c332662bbdf2cd1c829a9baabbd1fd98af4559500514719cde --node https://rpc-euphrates.devnet.babylonchain.io:443
finality_provider:
babylon_pk:
key: A5Htl6J2F/XDdL/SiSSrDa9vJ5hfuJRKYueVaQWxIefB
btc_pk: ae19288a43b107c332662bbdf2cd1c829a9baabbd1fd98af4559500514719cde
commission: "0.050000000000000000"
description:
details: ""
identity: ""
moniker: test gaia fp
security_contact: ""
website: ""
height: "0"
master_pub_rand: xpub661MyMwAqRbcFJoYM84xqYTzkf8XqvL2VLsogx4BDveFMcTDoAeXUBZgjsootUjuxnrfYCcCtcY9RiGoFt …
```
=> hotfix: fix consumer ID

clientcontroller/babylon/consumer.go
When error occurs, `block` is `nil` and `block.Height` will cause a nil pointer panic. Uncovered in local deployment
=> chore: fix nil pointer

itest/consumer_test_manager.go, itest/test_manager.go
The function [baseDir](https://github.com/babylonchain/finality-provider/blob/base/consumer-chain-support/itest/utils.go#L5) is the same as [tempDirWithName](https://github.com/babylonchain/finality-provider/blob/base/consumer-chain-support/itest/test_manager.go#L686), this PR removes the duplicate codes.
=> chore: remove duplicate codes

finality-provider/service/fp_instance.go
This PR fixes the error of fast sync for the consumer.
When the finality provider is not activated yet on the consumer, there is no need to catch up.
Also, we checked all where the function `tryFastSync` is called, and it would not block/break them when returning `nil`.
=> fix: fast sync for consumer

finality-provider/service/fp_instance.go
The PR reverts the commit of PR https://github.com/babylonchain/finality-provider/pull/401.
In Babylon, the BTC Staking protocol is activated means [there exists at least one active BTC delegation](https://github.com/babylonchain/babylon/tree/dev/x/btcstaking#beginblocker).
It would fail to query the activated height before the BTC delegation, so we need to revert the commit, and also update the QueryActivatedHeight logic in OPStackL2 consumer controller.
=> fix: revert the pr #401 commit

Makefile, clientcontroller/opstackl2/consumer.go
context https://github.com/babylonchain/finality-provider/issues/397
note that this just a workaround, we probably should avoid this happen in the first place
but this PR is good for now
=> chore: add `clean-e2e` command to kill dangling babylond or wasmd processed when e2e tests fails

Makefile, clientcontroller/opstackl2/consumer.go, finality-provider/service/fp_instance.go, itest/consumer_test_manager.go, itest/test_manager.go, itest/utils.go
our own e2e test will use those names
move them to utils.go
in the future, we should refactor to create independent packages for opl2, wasm, and babylon consumers but that's outside of the scope of this PR
```
make test-e2e
make test
```
=> refactor: expose a few private names from e2e test

clientcontroller/opstackl2/consumer.go
This PR fixes the issue of parsing cw data with null. When a cw contract's return data is `None`, the JSON is a four-character string `null` and the `json.Unmarshal()` does NOT raise an error. 
make test-e2e
=> fix: parse cw data with null

itest/consumer_test_manager.go, itest/opstackl2/op_test_manager.go, itest/test_manager.go
This PR fixed typos and duplicated codes.
```
make test-e2e
```
=> chore: fix typo and duplicated codes

Makefile, clientcontroller/babylon/babylon.go, itest/opstackl2/op_e2e_test.go, itest/opstackl2/op_test_manager.go
move a few helper methods from itest/opstackl2/op_e2e_test.go to itest/opstackl2/op_test_manager.go
also added `make lint` command to be consistent with CI. so next step we don't need to wait for CI to detect any lint issues
```
make lint
make test-e2e
make test
```
wait for CI tests
=> refactor: move some e2e methods

.golangci.yml, Makefile, clientcontroller/babylon/babylon.go, itest/opstackl2/op_e2e_test.go, itest/opstackl2/op_test_manager.go
to properly set up CI to lint tests
I can't add `e2e` tag b/c it fails lint. we need to fix it first: https://github.com/babylonchain/finality-provider/issues/414
manually add an unused var and it can detect issue when I run `make lint`
=> chore: add .golangci.yml

itest/e2e_test.go, itest/opstackl2/op_e2e_test.go, itest/opstackl2/op_test_manager.go, itest/test_manager.go, itest/utils.go
This PR refactors the e2e test for opstack l2 so that some common functions can be reused in other repos.
```
make test-e2e
```
=> test: refactor the e2e test for opstack l2

itest/opstackl2/op_e2e_test.go, itest/opstackl2/op_test_manager.go
since we are not doing BTC delegation, we won't encounter the `ErrNoBabylonFPRestaked` error here: https://github.com/babylonchain/babylon-private/blob/base/consumer-chain-support/x/btcstaking/keeper/btc_delegations.go#L212
I also removed some unnecessary logs
```
make lint
make test-e2e-op
```
=> fix: remove unused Babylon FP in e2e test

itest/babylon/babylon_test_manager.go
we need to use it in our own e2e to pass in both a Babylon FP and a Consumer FP
```
make test-e2e-babylon   
```
=> test: handle multiple providers in `InsertCovenantSigForDelegation`

itest/babylon/babylon_e2e_test.go, itest/babylon/babylon_test_manager.go, itest/opstackl2/op_e2e_test.go, itest/opstackl2/op_test_manager.go, itest/utils.go
no need to define twice in both the OP and BBN test manager
wait for CI
=> refactor: move `WaitForFpPubRandCommitted` to utils to dedup

itest/babylon/babylon_e2e_test.go, itest/opstackl2/op_e2e_test.go, itest/opstackl2/op_test_manager.go, itest/utils.go
This PR fixes the op e2e test issue which was caused by the block hash with the wrong format.
```
make test
make test-e2e
```
=> fix: op e2e test

clientcontroller/api/interface.go, clientcontroller/babylon/consumer.go, clientcontroller/cosmwasm/consumer.go, clientcontroller/opstackl2/consumer.go, clientcontroller/opstackl2/msg.go, finality-provider/service/app_test.go, finality-provider/service/fastsync_test.go, finality-provider/service/fp_instance.go, finality-provider/service/fp_instance_test.go, finality-provider/service/fp_manager_test.go, itest/babylon/babylon_e2e_test.go, itest/cosmwasm/bcd/bcd_consumer_e2e_test.go, itest/opstackl2/op_e2e_test.go, itest/opstackl2/op_test_manager.go, itest/utils.go, testutil/mocks/clientcontroller.go, types/pub_rand_commit.go
#407 
```
make lint
```
wait for CI
=> refactor: clean up interface `QueryLastCommittedPublicRand()`

clientcontroller/opstackl2/consumer.go
just realized that we have define this method in `finality-provider/config/opstackl2.go` but never used it
not sure why but let's add it
```
make lint
```
wait for CI
=> fix: add missing Config.Validate()

finality-provider/config/config.go, finality-provider/config/opstackl2.go, finality-provider/service/fp_instance.go, itest/babylon_node_handler.go, itest/opstackl2/op_test_manager.go, itest/utils.go
https://github.com/babylonchain/finality-provider/issues/449
also per @maurolacy's suggestion https://github.com/babylonchain/finality-provider/pull/447#discussion_r1660667470, I moved the logger changes to this PR
also added some other log related improvements in this PR
```
make lint
```
wait for CI
=> fix: non-op logger in itests

finality-provider/service/fastsync_test.go, finality-provider/service/fp_instance.go, finality-provider/service/fp_instance_test.go, finality-provider/service/fp_manager_test.go, itest/opstackl2/op_e2e_test.go, itest/opstackl2/op_test_manager.go, testutil/utils.go
see discussion here https://github.com/babylonchain/finality-provider/pull/447#discussion_r1660074723
let's first list the facts and requirements:
facts:
- first PR submissoin is based on tip height (e.g. height 27)
- chain poller starts from the lowest non-finalized height that the fp has not processed. (e.g. height 2)
- finalitySigSubmissionLoop receives signal from chain poller to try to submit sig from height 2 which will ofc fatal on max retry
requirements:
- we want to ensure no blocks with voting power will be missed
---
so I think the root cause is first PR submission shouldn't be determined by tipHeight. b/c it means the PR and Sig submission loops is not consistent in the start state.
my proposed fix is to add a global state firstPolledHeight that only be set once on the first …
=> fix: start height of initial public randomness commit

eotsmanager/cmd/eotsd/daemon/pop.go, eotsmanager/cmd/eotsd/daemon/pop_test.go, eotsmanager/cmd/eotsd/daemon/sign_test.go, eotsmanager/cmd/eotsd/main.go
This export of proof of possession is useful for building messages like `MsgCreateFinalityProvider`
Add new command `eotsd pop-export [bbn-addr] ... `
=> feat: add export of `ProofOfPossessionBTC` to `eotsd`

itest/opstackl2/op_test_manager.go
This PR resolves the problem that OP configuration does not take effect.
```
make lint
make test-e2e-op
```
=> fix: refactor op test manager

clientcontroller/cosmwasm/consumer.go, clientcontroller/opstackl2/consumer.go, cosmwasmclient/client/contract.go, itest/opstackl2/op_test_manager.go, testutil/json/json.go
duplicate code used by Cosmwams consumer, OP consumer, OP test manager. I extracted to `cosmwasmclient/client/contract.go`
```
make lint
```
wait for CI
=> refactor: extract common logic for CW contract operations

eotsmanager/localmanager.go
while using https://go.dev/doc/articles/race_detector to debug a nasty segfault issue in our own e2e test, we found this issue (https://github.com/babylonchain/finality-provider/issues/478).
first, add `-race` to the make target for running the e2e tests and run tests
before this PR, I saw:
```
==================
WARNING: DATA RACE
Write at 0x00c0089dfb80 by goroutine 102770:
strings.(*Reader).Reset()
/opt/homebrew/Cellar/go/1.22.4/libexec/src/strings/reader.go:156 +0x8c
github.com/babylonchain/finality-provider/eotsmanager.(*LocalEOTSManager).getEOTSPrivKey()
/Users/zidong/Documents/Projects/babylon-finality-provider/eotsmanager/localmanager.go:281 +0x6c
github.com/babylonchain/finality-provider/eotsmanager.(*LocalEOTSManager).KeyRecord() …
```
=> fix: data race in LocalEOTSManager

eotsmanager/localmanager.go
discussed w @SebastianElvis
no other good way than cherry-pick it as a separate PR to `dev`
=> (cherry-pick) fix: data race in LocalEOTSManager (#479)

clientcontroller/cosmwasm/consumer.go, finality-provider/service/chain_poller.go, finality-provider/service/fp_instance.go
This PR fixes a bug in CosmWasm consumer controller where we need to check whether the unmarshalled activated height is 0 or not. If it's 0 then it means we are unmarshalling something fishy and actually BTC staking is not activated, and we need to return an error, as [expected](https://github.com/babylonchain/finality-provider/blob/fee9b10e886a098ebd97b7ccfcf9e31bf465a746/finality-provider/service/chain_poller.go#L211-L220) by RPC poller. This fix allows us to remove some hacks and makes e2e / local deployment pass.
@gitferry Do you think in the [poller](https://github.com/babylonchain/finality-provider/blob/a531ebd36686383eb1424929ff95ca820a9b3c5c/finality-provider/service/chain_poller.go#L213-L214) we need to distinguish between the "BTC staking is not activated" and other errors? This …
=> cosmwasm: fix check of activated height in CosmWasm controller

itest/opstackl2/op_e2e_test.go, itest/opstackl2/op_test_manager.go
This PR splits into FP registration and FP instance startup in the op test manager. It is needed for the next test case: https://github.com/babylonchain/finality-provider/issues/502
```
make test-e2e-op
```
=> test: split into FP registration and FP instance startup in the op test manager

clientcontroller/api/interface.go, clientcontroller/babylon/babylon.go, clientcontroller/babylon/consumer.go, clientcontroller/cosmwasm/consumer.go, clientcontroller/opstackl2/consumer.go, finality-provider/service/app.go, finality-provider/service/app_test.go, finality-provider/service/fastsync_test.go, finality-provider/service/fp_instance.go, finality-provider/service/fp_instance_test.go, finality-provider/service/fp_manager.go, finality-provider/service/fp_manager_test.go, itest/opstackl2/op_e2e_test.go, testutil/mocks/clientcontroller.go
context in https://github.com/babylonchain/finality-provider/issues/496
this interface function is only used for checking if the FP is eligible for submitting sigs
per @SebastianElvis's suggestion, instead of querying the exact voting power, the FP queries BTC delegations page by page, and if there is >=1 active BTC delegation, then it can vote.
this PR first tightens the interface
next, I will work on the implementation per algorithm ^
```
make mock-gen
make lint
make test-e2e-babylon 
```
=> consumer: refactor: QueryFinalityProviderVotingPower -> QueryFinalityProviderHasPower

cosmwasmclient/client/client.go, cosmwasmclient/client/tx.go
fixing another data race.
it's caused by fast sync and the main sig submission loop calling `ReliablySendMsgs` function from the  same `cc.CwClient`
context: https://github.com/babylonchain/finality-provider/issues/478
first add `-race` in the make file command then run `make test-e2e-op`
before this PR I see:
<details><summary> data race messages</summary>
```
==================
WARNING: DATA RACE
Write at 0x00c0089a9330 by goroutine 355805:
cosmossdk.io/x/tx/signing.(*Context).makeGetSignersFunc.func5()
/Users/zidong/go/pkg/mod/cosmossdk.io/x/tx@v0.13.3/signing/context.go:311 +0xdc
cosmossdk.io/x/tx/signing.(*Context).GetSigners()
/Users/zidong/go/pkg/mod/cosmossdk.io/x/tx@v0.13.3/signing/context.go:357 +0x98
github.com/cosmos/cosmos-sdk/codec.ProtoCodec.GetMsgAnySigners() …
```
=> consumer: fix: data race in cosmwasmclient/client/client.go

Makefile, itest/opstackl2/op_e2e_test.go, itest/opstackl2/op_test_manager.go
This PR adds an op e2e test: 
* close https://github.com/babylonchain/finality-provider/issues/502
* check L2 finality will get stuck if one block didn't get enough votes 
* check L2 finality will recover if the block gets enough votes 
```
make test-e2e-op
```
=> test: check L2 finality will get stuck if one block didn't get enough votes

Makefile, finality-provider/service/fp_store_adapter.go, itest/opstackl2/op_e2e_test.go
This PR fixes the data race in these two functions using the `sync.Mutex`
* `GetLastProcessedHeight()` to fix the data race when running the bcd e2e test, below are the data race details
<details>
<summary> data race </summary>
```
==================
WARNING: DATA RACE
Write at 0x00c000c7a290 by goroutine 400:
github.com/babylonchain/finality-provider/finality-provider/service.(*fpState).setLastProcessedAndVotedHeight()
/Users/lyy/babylon/finality-provider/finality-provider/service/fp_store_adapter.go:101 +0x8c
github.com/babylonchain/finality-provider/finality-provider/service.(*FinalityProviderInstance).updateStateAfterFinalitySigSubmission()
/Users/lyy/babylon/finality-provider/finality-provider/service/fp_store_adapter.go:162 +0x48 …
```
=> fix: data race in `GetLastProcessedHeight()` and `GetLastVotedHeight()`

docs/eots.md, eotsmanager/cmd/eotsd/daemon/flags.go, eotsmanager/cmd/eotsd/daemon/pop.go, eotsmanager/cmd/eotsd/daemon/pop_test.go, eotsmanager/cmd/eotsd/daemon/sign.go, eotsmanager/cmd/eotsd/daemon/sign_test.go
This only changes the naming in flag and docs, suggested at https://github.com/babylonchain/pm/pull/67#discussion_r1677552147
=> chore: migrate from btc-pk to eots-pk in eotsd related commands and docs

finality-provider/cmd/fpd/daemon/flags.go, finality-provider/cmd/fpd/daemon/tx.go, finality-provider/cmd/fpd/daemon/tx_test.go, finality-provider/config/config.go
Add new command helper to validate signed `MsgCreateFinalityProvider` stored in file
Closes: https://github.com/babylonchain/finality-provider/issues/521
=> feat: add validate-signed-finality-provider command

itest/opstackl2/op_test_manager.go
https://github.com/babylonchain/finality-provider/pull/526#discussion_r1685900211
> how about we differentiate Babylon FP and consumer FP a bit, e.g., create a Babylon FP outside this for loop, and return a Babylon FP APP and a list of consumer FP APP? In this function they are mixed together. Same comments apply to createFpConfigs and StartOpL2ConsumerManager
so I changed
```
FpApp []*service.FinalityProviderApp
```
to
```
BabylonFpApp      *service.FinalityProviderApp
ConsumerFpApps    []*service.FinalityProviderApp
```
---
I also found a bug while doing this refactoring. in the op test manager we have
```
func (ctm *OpL2ConsumerTestManager) WaitForTargetBlockPubRand(...) {
require.Equal(t, 2, len(fpList), "The below algorithm only supports two FPs")
...
i := 1
targetBlockHeight = …
```
=> refactor FP e2e tests to differentiate Babylon FP and consumer FPs
